version: '3.8'

services:
  education-analyzer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python src/main.py
    restart: unless-stopped